package ooprepeatproject;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileWriter;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.IOException;
/**
 *
 * @author x16114388
 */
public class Questions extends javax.swing.JFrame {
private ArrayList<Integer> list;


Random rand = new Random();
GetterSetter score = new GetterSetter(); //new object called Score
    /**
     * Creates new form Questions
     */
    public Questions() {  
      
      list = new ArrayList<>();  
        
        
        initComponents();

    GetterSetter score = new GetterSetter(); //new object from GetterSetter class called Score

    jLblScore.setText(""+score.scoreMain); //label to get and set score
    jLabel1.setText("Question"+score.counter);

//hiding questions and answer buttons
    
    jTextName.setVisible(false);
    jBtnName.setVisible(false);

    jLabel2.setVisible(false); jLabel3.setVisible(false); jLabel4.setVisible(false);
    jLabel5.setVisible(false); jLabel6.setVisible(false); jLabel7.setVisible(false);
    jLabel8.setVisible(false); jLabel9.setVisible(false); jLabel10.setVisible(false);
    jLabel11.setVisible(false);

    jButton1.setVisible(false); jButton2.setVisible(false); jButton3.setVisible(false);
    jButton4.setVisible(false); jButton5.setVisible(false); jButton6.setVisible(false);
    jButton7.setVisible(false); jButton8.setVisible(false); jButton9.setVisible(false);
    jButton10.setVisible(false); jButton11.setVisible(false); jButton12.setVisible(false);
    jButton13.setVisible(false); jButton14.setVisible(false); jButton15.setVisible(false);
    jButton16.setVisible(false); jButton17.setVisible(false); jButton18.setVisible(false);
    jButton19.setVisible(false); jButton20.setVisible(false);
    
//Loop to generate Questions in Random Order

list.add(1); list.add(2); list.add(3); list.add(4); list.add(5); 
list.add(6); list.add(7); list.add(8); list.add(9); list.add(10);
   

int rnd = new Random().nextInt(list.size());  //selects a random element in array
            
     
    
if(null !=list.get(rnd)) //if arraylist is not empty, then in case 1 set jLabel and Buttons Visible(true).
switch (list.get(rnd)) {
    case 1:
        jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        break;
    case 2:
        jLabel3.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        break;
    case 3:
        jLabel4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        break;
    case 4:
        jLabel5.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        break;
    case 5:
        jLabel6.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        break;
    case 6:
        jLabel7.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        break;
    case 7:
        jLabel8.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        break;
    case 8:
        jLabel9.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        break;
    case 9:
        jLabel10.setVisible(true);
        jButton17.setVisible(true);
        jButton18.setVisible(true);
        break;
    case 10:
        jLabel11.setVisible(true);
        jButton19.setVisible(true);
        jButton20.setVisible(true);
        break;
    default:
        break;
}
list.remove(rnd); //remove the selected random element from the Arraylist
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLblScore = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jTextName = new javax.swing.JTextField();
        jBtnName = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel2.setText("Who is currently USA president?");

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel3.setText("Who was the first person to walk on the Moon?");

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel4.setText("Which animal is a feline?");

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel5.setText("How many moons does Mars have?");

        jLabel6.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel6.setText("Which band has the album Abbey Road?");

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel7.setText("Who was responsible for creating modern Computers?");

        jLabel8.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel8.setText("When was National College of Ireland founded?");

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel9.setText("What langauge is this app made in?");

        jLabel10.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel10.setText("What time does NCI's fees office close?");

        jLabel11.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLabel11.setText("In Computing, what does RAM stand for?");

        jLblScore.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jLblScore.setText("jLblScore");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Quiz! You will be asked random 5 questions out of 10 that are made");

        jButton21.setText("CLOSE APP");
        jButton21.setToolTipText("You will lose all progress if you quit");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton1.setText("H.Clinton");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton2.setText("D.Trump");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton3.setText("N.Armstrong");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton4.setText("M.Collins");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton5.setText("Hyena");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton6.setText("Ocelot");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton7.setText("One");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton8.setText("Two");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton9.setText("The Rolling Stones");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton10.setText("The Beatles");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton11.setText("A.Turning");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton12.setText("A.Einstien");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton13.setText("1953");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton14.setText("1999");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton15.setText("Java");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton16.setText("C++");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton17.setText("16:00");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton18.setText("20:00");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton19.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton19.setText("Real Analysis Modem");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });

        jButton20.setFont(new java.awt.Font("Rockwell", 0, 12)); // NOI18N
        jButton20.setText("Random Access Memory");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jBtnName.setText("Save Name");
        jBtnName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNameActionPerformed(evt);
            }
        });

        jButton22.setText("View High Score");
        jButton22.setToolTipText("displays names and ");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Rockwell", 0, 11)); // NOI18N
        jLabel13.setText("POINTS:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton12)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton13))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton16)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton14))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton20))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(90, 90, 90)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(54, 54, 54)
                                                .addComponent(jButton21))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButton2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnName)
                                    .addComponent(jButton22))))
                        .addContainerGap(78, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel12)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLblScore, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton21)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnName))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jButton3)
                            .addComponent(jButton4)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButton22)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jButton11)
                    .addComponent(jButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jButton13)
                    .addComponent(jButton14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jButton15)
                    .addComponent(jButton16))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jButton17)
                    .addComponent(jButton18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jButton19)
                    .addComponent(jButton20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//Correct Answer

//score.qC1();
//score.generateQuestion();

JOptionPane.showMessageDialog(null, "Correct!");
jLabel2.setVisible(false);
jButton1.setVisible(false);
jButton2.setVisible(false);
                    
        score.scoreMain++; //increments score by one
        score.counter++;  //increments counter by one

        jLblScore.setText(""+score.scoreMain); //label to get and set score
        jLabel1.setText("Question " + score.counter);

        if (score.counter == 6) //when the player goes past the 5th Question, display JOptionPane, jTextName, jBtnName
        {
            jTextName.setVisible(true);
            jBtnName.setVisible(true); 
            jLabel1.setVisible(false);
JOptionPane.showMessageDialog(null, "Great! just enter your name in the textfield");  
        }
        
        else{               
int rnd = new Random().nextInt(list.size());
               
if(null !=list.get(rnd))
switch (list.get(rnd)) {
    case 1:
        jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        break;
    case 2:
        jLabel3.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        break;
    case 3:
        jLabel4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        break;
    case 4:
        jLabel5.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        break;
    case 5:
        jLabel6.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        break;
    case 6:
        jLabel7.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        break;
    case 7:
        jLabel8.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        break;
    case 8:
        jLabel9.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        break;
    case 9:
        jLabel10.setVisible(true);
        jButton17.setVisible(true);
        jButton18.setVisible(true);
        break;
    case 10:
        jLabel11.setVisible(true);
        jButton19.setVisible(true);
        jButton20.setVisible(true);
        break;
    default:
        break;
}
list.remove(rnd);   
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//Wrong Answer      doesn't increment score

JOptionPane.showMessageDialog(null, "Wrong!");
jLabel2.setVisible(false);
jButton1.setVisible(false);
jButton2.setVisible(false);

        score.counter++;

        jLblScore.setText(""+score.scoreMain); //label to get and set score
        jLabel1.setText("Question " + score.counter);

        if (score.counter == 6) //when the player goes past the 5th Question, display JOptionPane, jTextName, jBtnName and stop delete array of questions
        {
            jTextName.setVisible(true);
            jBtnName.setVisible(true); 
            jLabel1.setVisible(false);
JOptionPane.showMessageDialog(null, "Great! just enter your name in the textfield");  
        } 
        
        else{               
int rnd = new Random().nextInt(list.size());
               
if(null !=list.get(rnd))
switch (list.get(rnd)) {
    case 1:
        jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        break;
    case 2:
        jLabel3.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        break;
    case 3:
        jLabel4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        break;
    case 4:
        jLabel5.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        break;
    case 5:
        jLabel6.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        break;
    case 6:
        jLabel7.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        break;
    case 7:
        jLabel8.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        break;
    case 8:
        jLabel9.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        break;
    case 9:
        jLabel10.setVisible(true);
        jButton17.setVisible(true);
        jButton18.setVisible(true);
        break;
    case 10:
        jLabel11.setVisible(true);
        jButton19.setVisible(true);
        jButton20.setVisible(true);
        break;
    default:
        break;
}
list.remove(rnd);   
        }         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//Correct Answer
JOptionPane.showMessageDialog(null, "Correct!");
jLabel3.setVisible(false);
jButton3.setVisible(false);
jButton4.setVisible(false);
                    
        score.scoreMain++; //increments score by one
        score.counter++;  //increments counter by one

        jLblScore.setText(""+score.scoreMain); //label to get and set score
        jLabel1.setText("Question " + score.counter);

        if (score.counter == 6) //when the player goes past the 5th Question, display JOptionPane, jTextName, jBtnName and stop delete array of questions
        {
            jTextName.setVisible(true);
            jBtnName.setVisible(true); 
            jLabel1.setVisible(false);
JOptionPane.showMessageDialog(null, "Great! just enter your name in the textfield");  
        }      
        
        else{               
int rnd = new Random().nextInt(list.size());
               
if(null !=list.get(rnd))
switch (list.get(rnd)) {
    case 1:
        jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        break;
    case 2:
        jLabel3.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        break;
    case 3:
        jLabel4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        break;
    case 4:
        jLabel5.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        break;
    case 5:
        jLabel6.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        break;
    case 6:
        jLabel7.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        break;
    case 7:
        jLabel8.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        break;
    case 8:
        jLabel9.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        break;
    case 9:
        jLabel10.setVisible(true);
        jButton17.setVisible(true);
        jButton18.setVisible(true);
        break;
    case 10:
        jLabel11.setVisible(true);
        jButton19.setVisible(true);
        jButton20.setVisible(true);
        break;
    default:
        break;
}
list.remove(rnd);   
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
//Wrong Answer
JOptionPane.showMessageDialog(null, "Wrong!");
jLabel3.setVisible(false);
jButton3.setVisible(false);
jButton4.setVisible(false);

        score.counter++;  //increments counter by one

        jLblScore.setText(""+score.scoreMain); //label to get and set score
        jLabel1.setText("Question " + score.counter);

        if (score.counter == 6) //when the player goes past the 5th Question, display JOptionPane, jTextName, jBtnName and stop delete array of questions
        {
            jTextName.setVisible(true);
            jBtnName.setVisible(true); 
            jLabel1.setVisible(false);
JOptionPane.showMessageDialog(null, "Great! just enter your name in the textfield");  
        } 
        
        else{               
int rnd = new Random().nextInt(list.size());
               
if(null !=list.get(rnd))
switch (list.get(rnd)) {
    case 1:
        jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        break;
    case 2:
        jLabel3.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        break;
    case 3:
        jLabel4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        break;
    case 4:
        jLabel5.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        break;
    case 5:
        jLabel6.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        break;
    case 6:
        jLabel7.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        break;
    case 7:
        jLabel8.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        break;
    case 8:
        jLabel9.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        break;
    case 9:
        jLabel10.setVisible(true);
        jButton17.setVisible(true);
        jButton18.setVisible(true);
        break;
    case 10:
        jLabel11.setVisible(true);
        jButton19.setVisible(true);
        jButton20.setVisible(true);
        break;
    default:
        break;
}
list.remove(rnd);   
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
//Wrong Answer
JOptionPane.showMessageDialog(null, "Wrong!");
jLabel4.setVisible(false);
jButton5.setVisible(false);
jButton6.setVisible(false);

        score.counter++;  //increments counter by one

        jLblScore.setText(""+score.scoreMain); //label to get and set score
        jLabel1.setText("Question " + score.counter);

        if (score.counter == 6) //when the player goes past the 5th Question, display JOptionPane, jTextName, jBtnName and stop delete array of questions
        {
            jTextName.setVisible(true);
            jBtnName.setVisible(true); 
            jLabel1.setVisible(false);
JOptionPane.showMessageDialog(null, "Great! just enter your name in the textfield");  
        }
        
        else{               
int rnd = new Random().nextInt(list.size());
               
if(null !=list.get(rnd))
switch (list.get(rnd)) {
    case 1:
        jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        break;
    case 2:
        jLabel3.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        break;
    case 3:
        jLabel4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        break;
    case 4:
        jLabel5.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        break;
    case 5:
        jLabel6.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        break;
    case 6:
        jLabel7.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        break;
    case 7:
        jLabel8.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        break;
    case 8:
        jLabel9.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        break;
    case 9:
        jLabel10.setVisible(true);
        jButton17.setVisible(true);
        jButton18.setVisible(true);
        break;
    case 10:
        jLabel11.setVisible(true);
        jButton19.setVisible(true);
        jButton20.setVisible(true);
        break;
    default:
        break;
}
list.remove(rnd);   
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
//Correct Answer
JOptionPane.showMessageDialog(null, "Correct!");
jLabel4.setVisible(false);
jButton5.setVisible(false);
jButton6.setVisible(false);
                    
        score.scoreMain++; //increments score by one
        score.counter++;  //increments counter by one

        jLblScore.setText(""+score.scoreMain); //label to get and set score
        jLabel1.setText("Question " + score.counter);

        if (score.counter == 6) //when the player goes past the 5th Question, display JOptionPane, jTextName, jBtnName and stop delete array of questions
        {
            jTextName.setVisible(true);
            jBtnName.setVisible(true); 
            jLabel1.setVisible(false);
JOptionPane.showMessageDialog(null, "Great! just enter your name in the textfield");  
        }      
        
        else{               
int rnd = new Random().nextInt(list.size());
               
if(null !=list.get(rnd))
switch (list.get(rnd)) {
    case 1:
        jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        break;
    case 2:
        jLabel3.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        break;
    case 3:
        jLabel4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        break;
    case 4:
        jLabel5.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        break;
    case 5:
        jLabel6.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        break;
    case 6:
        jLabel7.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        break;
    case 7:
        jLabel8.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        break;
    case 8:
        jLabel9.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        break;
    case 9:
        jLabel10.setVisible(true);
        jButton17.setVisible(true);
        jButton18.setVisible(true);
        break;
    case 10:
        jLabel11.setVisible(true);
        jButton19.setVisible(true);
        jButton20.setVisible(true);
        break;
    default:
        break;
}
list.remove(rnd);   
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
//Wrong Answer
JOptionPane.showMessageDialog(null, "Wrong!");
jLabel5.setVisible(false);
jButton7.setVisible(false);
jButton8.setVisible(false);

        score.counter++;  //increments counter by one

        jLblScore.setText(""+score.scoreMain); //label to get and set score
        jLabel1.setText("Question " + score.counter);

        if (score.counter == 6) //when the player goes past the 5th Question, display JOptionPane, jTextName, jBtnName and stop delete array of questions
        {
            jTextName.setVisible(true);
            jBtnName.setVisible(true); 
            jLabel1.setVisible(false);
JOptionPane.showMessageDialog(null, "Great! just enter your name in the textfield");  
        } 
        
        else{               
int rnd = new Random().nextInt(list.size());
               
if(null !=list.get(rnd))
switch (list.get(rnd)) {
    case 1:
        jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        break;
    case 2:
        jLabel3.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        break;
    case 3:
        jLabel4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        break;
    case 4:
        jLabel5.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        break;
    case 5:
        jLabel6.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        break;
    case 6:
        jLabel7.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        break;
    case 7:
        jLabel8.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        break;
    case 8:
        jLabel9.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        break;
    case 9:
        jLabel10.setVisible(true);
        jButton17.setVisible(true);
        jButton18.setVisible(true);
        break;
    case 10:
        jLabel11.setVisible(true);
        jButton19.setVisible(true);
        jButton20.setVisible(true);
        break;
    default:
        break;
}
list.remove(rnd);   
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
//Correct Answer
JOptionPane.showMessageDialog(null, "Correct!");
jLabel5.setVisible(false);
jButton7.setVisible(false);
jButton8.setVisible(false);
                    
        score.scoreMain++; //increments score by one
        score.counter++;  //increments counter by one

        jLblScore.setText(""+score.scoreMain); //label to get and set score
        jLabel1.setText("Question " + score.counter);

        if (score.counter == 6) //when the player goes past the 5th Question, display JOptionPane, jTextName, jBtnName and stop delete array of questions
        {
            jTextName.setVisible(true);
            jBtnName.setVisible(true);
            jLabel1.setVisible(false);
JOptionPane.showMessageDialog(null, "Great! just enter your name in the textfield");  
        }      
        
        else{               
int rnd = new Random().nextInt(list.size());
               
if(null !=list.get(rnd))
switch (list.get(rnd)) {
    case 1:
        jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        break;
    case 2:
        jLabel3.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        break;
    case 3:
        jLabel4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        break;
    case 4:
        jLabel5.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        break;
    case 5:
        jLabel6.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        break;
    case 6:
        jLabel7.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        break;
    case 7:
        jLabel8.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        break;
    case 8:
        jLabel9.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        break;
    case 9:
        jLabel10.setVisible(true);
        jButton17.setVisible(true);
        jButton18.setVisible(true);
        break;
    case 10:
        jLabel11.setVisible(true);
        jButton19.setVisible(true);
        jButton20.setVisible(true);
        break;
    default:
        break;
}
list.remove(rnd);   
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
//Wrong Answer
JOptionPane.showMessageDialog(null, "Wrong!");
jLabel6.setVisible(false);
jButton9.setVisible(false);
jButton10.setVisible(false);

        score.counter++;  //increments counter by one

        jLblScore.setText(""+score.scoreMain); //label to get and set score
        jLabel1.setText("Question " + score.counter);

        if (score.counter == 6) //when the player goes past the 5th Question, display JOptionPane, jTextName, jBtnName and stop delete array of questions
        {
            jTextName.setVisible(true);
            jBtnName.setVisible(true); 
            jLabel1.setVisible(false);
JOptionPane.showMessageDialog(null, "Great! just enter your name in the textfield");  
        } 
        
        
        else{               
int rnd = new Random().nextInt(list.size());
               
if(null !=list.get(rnd))
switch (list.get(rnd)) {
    case 1:
        jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        break;
    case 2:
        jLabel3.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        break;
    case 3:
        jLabel4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        break;
    case 4:
        jLabel5.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        break;
    case 5:
        jLabel6.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        break;
    case 6:
        jLabel7.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        break;
    case 7:
        jLabel8.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        break;
    case 8:
        jLabel9.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        break;
    case 9:
        jLabel10.setVisible(true);
        jButton17.setVisible(true);
        jButton18.setVisible(true);
        break;
    case 10:
        jLabel11.setVisible(true);
        jButton19.setVisible(true);
        jButton20.setVisible(true);
        break;
    default:
        break;
}
list.remove(rnd);   
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
//Correct Answer
JOptionPane.showMessageDialog(null, "Correct!");
jLabel6.setVisible(false);
jButton9.setVisible(false);
jButton10.setVisible(false);

                     
        score.scoreMain++; //increments score by one
        score.counter++;  //increments counter by one

        jLblScore.setText(""+score.scoreMain); //label to get and set score
        jLabel1.setText("Question " + score.counter);

        if (score.counter == 6) //when the player goes past the 5th Question, display JOptionPane, jTextName, jBtnName and stop delete array of questions
        {
            jTextName.setVisible(true);
            jBtnName.setVisible(true);
            jLabel1.setVisible(false);
JOptionPane.showMessageDialog(null, "Great! just enter your name in the textfield");  
        }      
        
        else{               
int rnd = new Random().nextInt(list.size());
               
if(null !=list.get(rnd))
switch (list.get(rnd)) {
    case 1:
        jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        break;
    case 2:
        jLabel3.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        break;
    case 3:
        jLabel4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        break;
    case 4:
        jLabel5.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        break;
    case 5:
        jLabel6.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        break;
    case 6:
        jLabel7.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        break;
    case 7:
        jLabel8.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        break;
    case 8:
        jLabel9.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        break;
    case 9:
        jLabel10.setVisible(true);
        jButton17.setVisible(true);
        jButton18.setVisible(true);
        break;
    case 10:
        jLabel11.setVisible(true);
        jButton19.setVisible(true);
        jButton20.setVisible(true);
        break;
    default:
        break;
}
list.remove(rnd);   
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
//Correct Answer
JOptionPane.showMessageDialog(null, "Correct!");
jLabel7.setVisible(false);
jButton11.setVisible(false);
jButton12.setVisible(false);

        score.scoreMain++; //increments score by one
        score.counter++;  //increments counter by one

        jLblScore.setText(""+score.scoreMain); //label to get and set score
        jLabel1.setText("Question " + score.counter);

        if (score.counter == 6) //when the player goes past the 5th Question, display JOptionPane, jTextName, jBtnName and stop delete array of questions
        {
            jTextName.setVisible(true);
            jBtnName.setVisible(true);
            jLabel1.setVisible(false);
JOptionPane.showMessageDialog(null, "Great! just enter your name in the textfield");  
        } 
        
        else{               
int rnd = new Random().nextInt(list.size());
               
if(null !=list.get(rnd))
switch (list.get(rnd)) {
    case 1:
        jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        break;
    case 2:
        jLabel3.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        break;
    case 3:
        jLabel4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        break;
    case 4:
        jLabel5.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        break;
    case 5:
        jLabel6.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        break;
    case 6:
        jLabel7.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        break;
    case 7:
        jLabel8.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        break;
    case 8:
        jLabel9.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        break;
    case 9:
        jLabel10.setVisible(true);
        jButton17.setVisible(true);
        jButton18.setVisible(true);
        break;
    case 10:
        jLabel11.setVisible(true);
        jButton19.setVisible(true);
        jButton20.setVisible(true);
        break;
    default:
        break;
}
list.remove(rnd);   
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
//Wrong Answer
JOptionPane.showMessageDialog(null, "Wrong!");
jLabel7.setVisible(false);
jButton11.setVisible(false);
jButton12.setVisible(false);

        score.counter++;  //increments counter by one

        jLblScore.setText(""+score.scoreMain); //label to get and set score
        jLabel1.setText("Question " + score.counter);

        if (score.counter == 6) //when the player goes past the 5th Question, display JOptionPane, jTextName, jBtnName and stop delete array of questions
        {
            jTextName.setVisible(true);
            jBtnName.setVisible(true); 
            jLabel1.setVisible(false);
JOptionPane.showMessageDialog(null, "Great! just enter your name in the textfield");  
        } 
        
        else{               
int rnd = new Random().nextInt(list.size());
               
if(null !=list.get(rnd))
switch (list.get(rnd)) {
    case 1:
        jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        break;
    case 2:
        jLabel3.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        break;
    case 3:
        jLabel4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        break;
    case 4:
        jLabel5.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        break;
    case 5:
        jLabel6.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        break;
    case 6:
        jLabel7.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        break;
    case 7:
        jLabel8.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        break;
    case 8:
        jLabel9.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        break;
    case 9:
        jLabel10.setVisible(true);
        jButton17.setVisible(true);
        jButton18.setVisible(true);
        break;
    case 10:
        jLabel11.setVisible(true);
        jButton19.setVisible(true);
        jButton20.setVisible(true);
        break;
    default:
        break;
}
list.remove(rnd);   
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
//Correct Answer
JOptionPane.showMessageDialog(null, "Correct!");
jLabel8.setVisible(false);
jButton13.setVisible(false);
jButton14.setVisible(false);

        score.scoreMain++; //increments score by one
        score.counter++;  //increments counter by one

        jLblScore.setText(""+score.scoreMain); //label to get and set score
        jLabel1.setText("Question " + score.counter);

        if (score.counter == 6) //when the player goes past the 5th Question, display JOptionPane, jTextName, jBtnName and stop delete array of questions
        {
            jTextName.setVisible(true);
            jBtnName.setVisible(true);
            jLabel1.setVisible(false);
JOptionPane.showMessageDialog(null, "Great! just enter your name in the textfield");  
        } 
        
        else{               
int rnd = new Random().nextInt(list.size());
               
if(null !=list.get(rnd))
switch (list.get(rnd)) {
    case 1:
        jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        break;
    case 2:
        jLabel3.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        break;
    case 3:
        jLabel4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        break;
    case 4:
        jLabel5.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        break;
    case 5:
        jLabel6.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        break;
    case 6:
        jLabel7.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        break;
    case 7:
        jLabel8.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        break;
    case 8:
        jLabel9.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        break;
    case 9:
        jLabel10.setVisible(true);
        jButton17.setVisible(true);
        jButton18.setVisible(true);
        break;
    case 10:
        jLabel11.setVisible(true);
        jButton19.setVisible(true);
        jButton20.setVisible(true);
        break;
    default:
        break;
}
list.remove(rnd);   
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
//Wrong Answer
JOptionPane.showMessageDialog(null, "Wrong!");
jLabel8.setVisible(false);
jButton13.setVisible(false);
jButton14.setVisible(false);

        score.counter++;  //increments counter by one

        jLblScore.setText(""+score.scoreMain); //label to get and set score
        jLabel1.setText("Question " + score.counter);

        if (score.counter == 6) //when the player goes past the 5th Question, display JOptionPane, jTextName, jBtnName and stop delete array of questions
        {
            jTextName.setVisible(true);
            jBtnName.setVisible(true); 
            jLabel1.setVisible(false);
JOptionPane.showMessageDialog(null, "Great! just enter your name in the textfield");  
        } 
        
        else{               
int rnd = new Random().nextInt(list.size());
               
if(null !=list.get(rnd))
switch (list.get(rnd)) {
    case 1:
        jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        break;
    case 2:
        jLabel3.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        break;
    case 3:
        jLabel4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        break;
    case 4:
        jLabel5.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        break;
    case 5:
        jLabel6.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        break;
    case 6:
        jLabel7.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        break;
    case 7:
        jLabel8.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        break;
    case 8:
        jLabel9.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        break;
    case 9:
        jLabel10.setVisible(true);
        jButton17.setVisible(true);
        jButton18.setVisible(true);
        break;
    case 10:
        jLabel11.setVisible(true);
        jButton19.setVisible(true);
        jButton20.setVisible(true);
        break;
    default:
        break;
}
list.remove(rnd);   
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
//Correct Answer
JOptionPane.showMessageDialog(null, "Correct!");
jLabel9.setVisible(false);
jButton15.setVisible(false);
jButton16.setVisible(false);

        score.scoreMain++; //increments score by one
        score.counter++;  //increments counter by one

        jLblScore.setText(""+score.scoreMain); //label to get and set score
        jLabel1.setText("Question " + score.counter);

        if (score.counter == 6) //when the player goes past the 5th Question, display JOptionPane, jTextName, jBtnName and stop delete array of questions
        {
            jTextName.setVisible(true);
            jBtnName.setVisible(true); 
            jLabel1.setVisible(false);
JOptionPane.showMessageDialog(null, "Great! just enter your name in the textfield");  
        } 
        
        else{               
int rnd = new Random().nextInt(list.size());
               
if(null !=list.get(rnd))
switch (list.get(rnd)) {
    case 1:
        jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        break;
    case 2:
        jLabel3.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        break;
    case 3:
        jLabel4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        break;
    case 4:
        jLabel5.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        break;
    case 5:
        jLabel6.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        break;
    case 6:
        jLabel7.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        break;
    case 7:
        jLabel8.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        break;
    case 8:
        jLabel9.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        break;
    case 9:
        jLabel10.setVisible(true);
        jButton17.setVisible(true);
        jButton18.setVisible(true);
        break;
    case 10:
        jLabel11.setVisible(true);
        jButton19.setVisible(true);
        jButton20.setVisible(true);
        break;
    default:
        break;
}
list.remove(rnd);   
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
//Wrong Answer
JOptionPane.showMessageDialog(null, "Wrong!");
jLabel9.setVisible(false);
jButton15.setVisible(false);
jButton16.setVisible(false);

        score.counter++;  //increments counter by one

        jLblScore.setText(""+score.scoreMain); //label to get and set score
        jLabel1.setText("Question " + score.counter);

        if (score.counter == 6) //when the player goes past the 5th Question, display JOptionPane, jTextName, jBtnName and stop delete array of questions
        {
            jTextName.setVisible(true);
            jBtnName.setVisible(true); 
            jLabel1.setVisible(false);
JOptionPane.showMessageDialog(null, "Great! just enter your name in the textfield");  
        } 
        
        else{               
int rnd = new Random().nextInt(list.size());
               
if(null !=list.get(rnd))
switch (list.get(rnd)) {
    case 1:
        jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        break;
    case 2:
        jLabel3.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        break;
    case 3:
        jLabel4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        break;
    case 4:
        jLabel5.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        break;
    case 5:
        jLabel6.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        break;
    case 6:
        jLabel7.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        break;
    case 7:
        jLabel8.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        break;
    case 8:
        jLabel9.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        break;
    case 9:
        jLabel10.setVisible(true);
        jButton17.setVisible(true);
        jButton18.setVisible(true);
        break;
    case 10:
        jLabel11.setVisible(true);
        jButton19.setVisible(true);
        jButton20.setVisible(true);
        break;
    default:
        break;
}
list.remove(rnd);   
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
//Correct Answer
JOptionPane.showMessageDialog(null, "Correct!");
jLabel10.setVisible(false);
jButton17.setVisible(false);
jButton18.setVisible(false);

        score.scoreMain++; //increments score by one
        score.counter++;  //increments counter by one

        jLblScore.setText(""+score.scoreMain); //label to get and set score
        jLabel1.setText("Question " + score.counter);

        if (score.counter == 6) //when the player goes past the 5th Question, display JOptionPane, jTextName, jBtnName and stop delete array of questions
        {
            jTextName.setVisible(true);
            jBtnName.setVisible(true);
            jLabel1.setVisible(false);
JOptionPane.showMessageDialog(null, "Great! just enter your name in the textfield");  
        } 
        
        else{               
int rnd = new Random().nextInt(list.size());
               
if(null !=list.get(rnd))
switch (list.get(rnd)) {
    case 1:
        jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        break;
    case 2:
        jLabel3.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        break;
    case 3:
        jLabel4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        break;
    case 4:
        jLabel5.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        break;
    case 5:
        jLabel6.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        break;
    case 6:
        jLabel7.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        break;
    case 7:
        jLabel8.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        break;
    case 8:
        jLabel9.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        break;
    case 9:
        jLabel10.setVisible(true);
        jButton17.setVisible(true);
        jButton18.setVisible(true);
        break;
    case 10:
        jLabel11.setVisible(true);
        jButton19.setVisible(true);
        jButton20.setVisible(true);
        break;
    default:
        break;
}
list.remove(rnd);   
        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
//Wrong Answer
JOptionPane.showMessageDialog(null, "Wrong!");
jLabel10.setVisible(false);
jButton17.setVisible(false);
jButton18.setVisible(false);

        score.counter++;  //increments counter by one

        jLblScore.setText(""+score.scoreMain); //label to get and set score
        jLabel1.setText("Question " + score.counter);

        if (score.counter == 6) //when the player goes past the 5th Question, display JOptionPane, jTextName, jBtnName and stop delete array of questions
        {
            jTextName.setVisible(true);
            jBtnName.setVisible(true); 
            jLabel1.setVisible(false);
JOptionPane.showMessageDialog(null, "Great! just enter your name in the textfield");  
        } 
        
        else{               
int rnd = new Random().nextInt(list.size());
               
if(null !=list.get(rnd))
switch (list.get(rnd)) {
    case 1:
        jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        break;
    case 2:
        jLabel3.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        break;
    case 3:
        jLabel4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        break;
    case 4:
        jLabel5.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        break;
    case 5:
        jLabel6.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        break;
    case 6:
        jLabel7.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        break;
    case 7:
        jLabel8.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        break;
    case 8:
        jLabel9.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        break;
    case 9:
        jLabel10.setVisible(true);
        jButton17.setVisible(true);
        jButton18.setVisible(true);
        break;
    case 10:
        jLabel11.setVisible(true);
        jButton19.setVisible(true);
        jButton20.setVisible(true);
        break;
    default:
        break;
}
list.remove(rnd);   
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
//Wrong Answer
JOptionPane.showMessageDialog(null, "Wrong!");
jLabel11.setVisible(false);
jButton19.setVisible(false);
jButton20.setVisible(false);

        score.counter++;  //increments counter by one

        jLblScore.setText(""+score.scoreMain); //label to get and set score
        jLabel1.setText("Question " + score.counter);

        if (score.counter == 6) //when the player goes past the 5th Question, display JOptionPane, jTextName, jBtnName and stop delete array of questions
        {
            jTextName.setVisible(true);
            jBtnName.setVisible(true); 
            jLabel1.setVisible(false);
JOptionPane.showMessageDialog(null, "Great! just enter your name in the textfield");  
        } 
        
        else{               
int rnd = new Random().nextInt(list.size());
               
if(null !=list.get(rnd))
switch (list.get(rnd)) {
    case 1:
        jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        break;
    case 2:
        jLabel3.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        break;
    case 3:
        jLabel4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        break;
    case 4:
        jLabel5.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        break;
    case 5:
        jLabel6.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        break;
    case 6:
        jLabel7.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        break;
    case 7:
        jLabel8.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        break;
    case 8:
        jLabel9.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        break;
    case 9:
        jLabel10.setVisible(true);
        jButton17.setVisible(true);
        jButton18.setVisible(true);
        break;
    case 10:
        jLabel11.setVisible(true);
        jButton19.setVisible(true);
        jButton20.setVisible(true);
        break;
    default:
        break;
}
list.remove(rnd);   
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
//Correct Answer
JOptionPane.showMessageDialog(null, "Correct!");
jLabel11.setVisible(false);
jButton19.setVisible(false);
jButton20.setVisible(false);

        score.scoreMain++; //increments score by one
        score.counter++;  //increments counter by one

        jLblScore.setText(""+score.scoreMain); //label to get and set score
        jLabel1.setText("Question " + score.counter);

        if (score.counter == 6) //when the player goes past the 5th Question, display JOptionPane, jTextName, jBtnName and stop delete array of questions
        {
            jTextName.setVisible(true);
            jBtnName.setVisible(true); 
            jLabel1.setVisible(false);
JOptionPane.showMessageDialog(null, "Great! just enter your name in the textfield");  
        } 
        
        else{               
int rnd = new Random().nextInt(list.size());
               
if(null !=list.get(rnd))
switch (list.get(rnd)) {
    case 1:
        jLabel2.setVisible(true);
        jButton1.setVisible(true);
        jButton2.setVisible(true);
        break;
    case 2:
        jLabel3.setVisible(true);
        jButton3.setVisible(true);
        jButton4.setVisible(true);
        break;
    case 3:
        jLabel4.setVisible(true);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        break;
    case 4:
        jLabel5.setVisible(true);
        jButton7.setVisible(true);
        jButton8.setVisible(true);
        break;
    case 5:
        jLabel6.setVisible(true);
        jButton9.setVisible(true);
        jButton10.setVisible(true);
        break;
    case 6:
        jLabel7.setVisible(true);
        jButton11.setVisible(true);
        jButton12.setVisible(true);
        break;
    case 7:
        jLabel8.setVisible(true);
        jButton13.setVisible(true);
        jButton14.setVisible(true);
        break;
    case 8:
        jLabel9.setVisible(true);
        jButton15.setVisible(true);
        jButton16.setVisible(true);
        break;
    case 9:
        jLabel10.setVisible(true);
        jButton17.setVisible(true);
        jButton18.setVisible(true);
        break;
    case 10:
        jLabel11.setVisible(true);
        jButton19.setVisible(true);
        jButton20.setVisible(true);
        break;
    default:
        break;
}
list.remove(rnd);   
        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        //CLOSE APP
        System.exit(0);
    }//GEN-LAST:event_jButton21ActionPerformed

    private void jBtnNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNameActionPerformed
//Writes Name and points to highScores.text

 if (jTextName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a name in Textbox.","WARNING", JOptionPane.WARNING_MESSAGE);
        } //If a name is entered, it will be saved to highScores.txt
        else {
            File outFile;
            FileWriter fw;
            BufferedWriter bw;

            String name = jTextName.getText();
            String highScore = jLblScore.getText();
            try {
                outFile = new File("highScores.txt");
                fw = new FileWriter(outFile, true); //true will save many names
                bw = new BufferedWriter(fw);

                bw.write(name);
                bw.newLine();
                bw.write(highScore);
                bw.newLine();
                 //makes a new line for each name submitted

                bw.close();
                JOptionPane.showMessageDialog(null, "Name: " + name + " Score: " + highScore);
                
               jBtnName.setVisible(false);
               jTextName.setVisible(false);
                
            } catch (IOException e) {
                System.out.println("ERROR writing name to highScores.txt" + e);
            }
        }
    }//GEN-LAST:event_jBtnNameActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
//Reads player highscore
        String name;
        String highScore;
                
        File inFile;
        FileReader fr;
        BufferedReader br;
        
        try{
            inFile = new File("highScores.txt");
            fr = new FileReader(inFile);
            br = new BufferedReader(fr);
            
            name = br.readLine();
            highScore = br.readLine();
            while(name !=null && highScore !=null)
                {

                 JOptionPane.showMessageDialog(null, "NAME: " + name + " HIGHSCORE: " + highScore);
                    name = br.readLine();
             
                    highScore = br.readLine();
                }
    
            br.close();
        }
        
        catch(IOException e) {
        System.out.println("ERROR reading from highScores.txt" + e);
    }
    }//GEN-LAST:event_jButton22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Questions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblScore;
    private javax.swing.JTextField jTextName;
    // End of variables declaration//GEN-END:variables

}
